### ISSUE TITLE
bf16 precision was requested but not available on this hardware. Please use fp32 precision instead.

### ISSUE THREAD

**Issue by avoiteh** [EvilFreelancer/impruver#2]
Ох...

(venv) c:\user\impruver>python train_transformers.py configs/ruGPT35_13B_lora.yml --report-to=wandb
loading file vocab.json from cache at C:\Users\Parser\.cache\huggingface\hub\models--ai-forever--ruGPT-3.5-13B\snapshots\64b115374b8f086ef13ccb8ba4f49d8076a53324\vocab.json
loading file merges.txt from cache at C:\Users\Parser\.cache\huggingface\hub\models--ai-forever--ruGPT-3.5-13B\snapshots\64b115374b8f086ef13ccb8ba4f49d8076a53324\merges.txt
loading file tokenizer.json from cache at None
loading file added_tokens.json from cache at None
loading file special_tokens_map.json from cache at C:\Users\Parser\.cache\huggingface\hub\models--ai-forever--ruGPT-3.5-13B\snapshots\64b115374b8f086ef13ccb8ba4f49d8076a53324\special_tokens_map.json
loading file tokenizer_config.json from cache at C:\Users\Parser\.cache\huggingface\hub\models--ai-forever--ruGPT-3.5-13B\snapshots\64b115374b8f086ef13ccb8ba4f49d8076a53324\tokenizer_config.json
tokenizer config file saved in ./models/ruGPT35_13B_lora\tokenizer_config.json
Special tokens file saved in ./models/ruGPT35_13B_lora\special_tokens_map.json
Traceback (most recent call last):
  File "c:\user\impruver\train_transformers.py", line 206, in <module>
    fire.Fire(train)
  File "c:\user\impruver\venv\lib\site-packages\fire\core.py", line 135, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "c:\user\impruver\venv\lib\site-packages\fire\core.py", line 468, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "c:\user\impruver\venv\lib\site-packages\fire\core.py", line 684, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "c:\user\impruver\train_transformers.py", line 116, in train
    dtype = get_dtype(config["model"]["dtype"])
  File "c:\user\impruver\impruver\utils\get_dtype.py", line 37, in get_dtype
    raise RuntimeError(
RuntimeError: bf16 precision was requested but not available on this hardware. Please use fp32 precision instead.

**Comment by avoiteh** [comment]
RuntimeError: CUDA is required but not available for bitsandbytes. Please consider installing the multi-platform enabled version of bitsandbytes, which is currently a work in progress. Please check currently supported platforms and installation instructions at https://huggingface.co/docs/bitsandbytes/main/en/installation#multi-backend

Хотя CUDA есть :(

**Comment by EvilFreelancer** [comment]
Привет! Точность fp32 это формат который используется при обучении на процессорах, иными словами драйвер CUDA встал некорректно, либо же он слишком устарел, поэтому bnb не может выполнить квантование весов на лету.

В чате канала https://t.me/evilfreelancer стало известно, что ты пытаешься запустить обучение на GPT710, а эта карточка уже давно не поддерживается в драйверах Nvidia и CUDA, так что для начала стоит попробовать карточку поновее, минимум GT1050, а лучше сразу что-то с 16Гб видеопамяти или выше, скаже RTX 4060ti или RTX 4070.
